-- migrations/{FILENAME}
--
-- DO NOT EDIT MIGRATION FILES BY HAND ONCE MERGED.
-- Migrations are append-only. New schema changes go in a new file:
--   migrations/000N_<name>.sql  (N = next number, ascending)
-- The deploy pipeline applies them in order.
--
-- Request: {REQUEST}
-- Generated by the generate-migration skill; checked by the migration-verifier subagent.
--
-- Rollback: the block under the ROLLBACK marker undoes this migration exactly. It stays
-- commented out and is run only on an approved revert.

{FORWARD_SQL}

-- ROLLBACK
-- {ROLLBACK_SQL}
