-- migrations/0002_add_orders_notes.sql
--
-- DO NOT EDIT MIGRATION FILES BY HAND ONCE MERGED.
-- Migrations are append-only. New schema changes go in a new file:
--   migrations/000N_<name>.sql  (N = next number, ascending)
-- The deploy pipeline applies them in order.
--
-- Request: Add a notes column to the orders table so support can leave free-text comments on an order. It's optional.
-- Generated by the generate-migration skill; checked by the migration-verifier subagent.
--
-- Rollback: the block under the ROLLBACK marker undoes this migration exactly. It stays
-- commented out and is run only on an approved revert.

ALTER TABLE orders ADD COLUMN IF NOT EXISTS notes TEXT;

-- ROLLBACK
-- ALTER TABLE orders DROP COLUMN IF EXISTS notes;
